create table public.users (
  user_id text not null,
  full_name text not null,
  designation text null,
  department text null,
  date_of_birth date null,
  gender text null,
  email text null,
  phone_number text null,
  current_address text null,
  username text not null,
  password text not null,
  role text null,
  is_active boolean null default true,
  profile_picture text null,

  created_at timestamp without time zone
  default (now() at time zone 'Asia/Kolkata'),

  page_access text[] null default '{}'::text[],

  constraint users_pkey primary key (user_id),
  constraint users_username_key unique (username)
) TABLESPACE pg_default;



create table public.orders (
  id bigint generated by default as identity primary key,
  
  -- Order Details
  order_date date not null,
  challan_name text null,
  customer_name text not null,
  customer_type text null,
  site_poc_contact text null,
  
  -- Location
  state text null,
  city text null,
  delivery_address text null,
  
  -- Items (stored as JSON array: [{product, quantity, price, points}, ...])
  items jsonb default '[]'::jsonb,
  total_amount numeric(15, 2) default 0.00,
  
  -- Points & Roles
  point_role text null,
  
  -- Logistics & Payment
  logistics_option text null,
  payment_terms text null,
  manual_payment_days int null,
  
  -- Meta
  notes text null,
  status text default 'Pending',
  
  -- Creator Details (Logged in user)
  created_by_user_id text not null references public.users(user_id),
  created_by_user_name text not null,
  
  -- Timestamp (Matches your users table pattern)
  created_at timestamp without time zone default (now() at time zone 'Asia/Kolkata')
) tablespace pg_default;

